title: Sharif Orzikulov # your name (or website title) here
logo: "/images/plus_155.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  5+ years of Business Analyst and IT Consultant experience with extensive international experience. 
  Possess Bachelor's Degree in Information Technology from Tashkent University of Information Technoligies in Tashkent, Uzbekistan.
  <br><br>
  Currently in the IBM Hybrid Cloud Software Group serving as Digital Business Automation Specialist. 
  I'm on the North American team, working with US customers in the Industrial and Distribution market.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
